title: Girls Adoption Connect
url: "https://girlsadoptionconnect.org"
baseurl: "" 
permalink: /post/:slug/

plugins:
  - jekyll-seo-tag

google_site_verification: <meta name="google-site-verification" content="1BMPLF1YxN6n3qqk2Lip2vzMOpk7519HvYoa7f9ygMA" />
